### ISSUE TITLE
What Can GitHub Tell Us About the HDL Industry? (Part 3)

### ISSUE THREAD

**Issue by umarcor** [VHDL/news#11]
```yaml
ref: https://larsasplund.github.io/github-facts/verification-practices.html#users
repo: LarsAsplund/github-facts
related: [2, 3, 6]
tags:
- cocotb
- osvvm
- study
- uvm
- uvvm
- verification
- vunit
```

The third part was published:

> In the [second article](https://www.linkedin.com/pulse/what-can-github-tell-us-hdl-industry-part-2-lars-asplund/?lipi=urn%3Ali%3Apage%3Ad_flagship3_pulse_read%3BRpGDGc%2FFRCe1jX5%2B2RRRJQ%3D%3D) about our GitHub study we analyzed the popularity of standard verification frameworks in VHDL repositories. This time we extend on those findings by analyzing the Git history of those repositories to find the number of users and examine how that changed over time.
> 
> [![IMAGE ALT TEXT](http://img.youtube.com/vi/Rs8ojJAE9ec/0.jpg)](http://www.youtube.com/watch?v=Rs8ojJAE9ec "Video Title")
>
> Looking at users rather than repositories doesn’t have a drastic effect to the overall picture. VUnit is still the most commonly used verification framework on GitHub. However, when separating professional and academic users we're starting to see interesting differences and anomalies in the data.
> 
> The [full story](https://larsasplund.github.io/github-facts/) and [the code](https://github.com/LarsAsplund/github-facts) used to derive these facts are part of an [open science](https://en.wikipedia.org/wiki/Open_science) project. Everything can be reviewed and the results can be repeated. We encourage [contributions](https://github.com/LarsAsplund/github-facts/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc) and [suggestions](https://github.com/LarsAsplund/github-facts/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) on other interesting facts that we should derive.
>
> -- _Lars Asplund_ [linkedin.com/pulse/what-can-github-tell-us-hdl-industry-part-3-lars-asplund/](https://www.linkedin.com/pulse/what-can-github-tell-us-hdl-industry-part-3-lars-asplund/)
