### ISSUE TITLE
SusanaCanel - Proyectos VHDL

### ISSUE THREAD

**Issue by umarcor** [VHDL/news#15]
```yaml
ref: https://www.youtube.com/c/SusanaCanel
repo: https://github.com/susanacanel/proyectos-vhdl
tags:
- learning
- teaching
- exercises
- videos
- youtube
- modelsim
- ghdl
- altera
```

Youtube channel [SusanaCanel](https://www.youtube.com/c/SusanaCanel) contains 100+ videos (in spanish) about learning VHDL. The GitHub [repository](https://github.com/susanacanel/proyectos-vhdl) contains the sources used in the videos.
