### ISSUE TITLE
Combining VUnit tests with cocotb components

### ISSUE THREAD

**Issue by umarcor** [VHDL/news#16]
```yaml
ref: https://github.com/umarcor/vunit-cocotb/blob/master/README.md
tags: [vunit, cocotb, python, testing, verification, co-simulation, simulation, ghdl]
repo: umarcor/vunit-cocotb
```
