### ISSUE TITLE
Docker dashboard (on Windows and Mac OS)

### ISSUE THREAD

**Issue by eine** [VHDL/news#18]
```yaml
ref: https://www.docker.com/blog/the-docker-dashboard-welcomes-hub-and-local-images/
repo: ghdl/docker
tags:
  - docker
  - container
  - simulation
  - synthesis
  - programming
```
