### ISSUE TITLE
What are the chances of having sb_ice40_components_syn.vhd freely distributed for the benefit of the community?

### ISSUE THREAD

**Issue by umarcor** [VHDL/news#19]
```yaml
ref: https://www.linkedin.com/posts/rodrigoalejandromelo_fpga-activity-6720313853093130240-MeQH/
tags:
  - lattice
  - ice40
  - vhdl
  - components
  - synthesis
  - ghdl-yosys-plugin
```
