### ISSUE TITLE
Microwatt and GHDL - An Open Hardware CPU written in VHDL, Synthesized with Open Source Tools

### ISSUE THREAD

**Issue by umarcor** [VHDL/news#21]
```yaml
ref: https://www.youtube.com/watch?v=N-_9dWdvLBA
tags: [microwatt, ghdl, simulation, synthesis, power, openisa]
repo: antonblanchard/microwatt
```

> Microwatt and GHDL - An Open Hardware CPU written in VHDL, Synthesized with Open Source Tools
> 
> Speakers: Anton Blanchard, IBM & Tristan Gingold, CERN
> 
> Microwatt is a 64 bit POWER OpenISA soft processor, written in VHDL. Over time it has grown from supporting Micropython, to Zephyr and most recently Linux.
>
> From its original inception, Microwatt has relied heavily on GHDL, the Open Source VHDL simulator. GHDL has very recently added synthesis support and together with Yosys and Nextpnr allows for a completely open source toolchain for FPGAs.
>
> This presentation will give an overview of the Microwatt core. It will also include an overview of GHDL and how it can be used for both simulation and synthesis of a medium complexity VHDL project.
