### ISSUE TITLE
Building and deploying container images for open source EDA

### ISSUE THREAD

**Issue by eine** [VHDL/news#23]
```yaml
ref: https://hdl.github.io/containers
tags: [debian, docker, podman, ghdl, yosys, nextpnr, gtkwave, icestorm, prjtrellis, symbiyosys, z3]
repo: hdl/containers
```

> [hdl/containers: README.md](https://github.com/hdl/containers/blob/master/README.md)
> This repository contains scripts and GitHub Actions (GHA) YAML workflows for building, testing and deploying OCI images (aka Docker images) including open source EDA tooling. All of them are pushed to [hub.docker.com/u/hdlc](https://hub.docker.com/u/hdlc). See [hdl.github.io/containers](https://hdl.github.io/containers) for further details and contributing guidelines.

> [ghdl/docker: DEPRECATED.md](https://github.com/ghdl/docker/blob/master/DEPRECATED.md)
> Some images related to synthesis and PnR were moved to [hdl/containers](https://github.com/hdl/containers) and [hub.docker.com/u/hdlc](https://hub.docker.com/u/hdlc). Some of those are now mirrored to `ghdl/synth:*` for backwards compatibility, but are no longer built in this repository.
