### ISSUE TITLE
Mixed HDL on Fomu, with GHDL and Yosys

### ISSUE THREAD

**Issue by umarcor** [VHDL/news#26]
```yaml
ref: https://im-tomu.github.io/fomu-workshop/mixed-hdl
tags: [vhdl, verilog, GHDL, yosys, synthesis, fomu, workshop, examples]
repo: im-tomu/fomu-workshop
```

Section [Mixed HDL on Fomu](https://im-tomu.github.io/fomu-workshop/mixed-hdl) of the [FPGA Tomu Workshop](https://im-tomu.github.io/fomu-workshop/index.html) contains Makefile based examples for synthesising mixed language (VHDL and Verilog) designs using open source tooling. Find sources at [im-tomu/fomu-workshop: mixed-hdl/blink](https://github.com/im-tomu/fomu-workshop/tree/master/mixed-hdl/blink).

NOTE: The workshop uses [im-tomu/fomu-toolchain](https://github.com/im-tomu/fomu-toolchain), which is based on [open-tool-forge/fpga-toolchain](https://github.com/open-tool-forge/fpga-toolchain). Hence, makefiles expect ghdl-yosys-plugin to be built into Yosys. Other packaging solutions can be used too, but using ghdl-yosys-plugin as a module requires adding `-m ghdl` to the yosys call in the Makefile.
