### ISSUE TITLE
MINGW-packages for Electronic Design Automation (EDA)

### ISSUE THREAD

**Issue by umarcor** [VHDL/news#27]
```yaml
ref: https://hdl.github.io/MINGW-packages
tags: [MSYS2, Windows, package, EDA, fritzing, GHDL, ghdl-yosys-plugin, Graphviz, GTKWave, icestorm, iverilog, KiCad, nextpnr, ngspice, prjtrellis, verilator, yices2, yosys, dfu-util, eccprog, icesprog, openFPGALoader, OpenOCD]
related: [20, 23]
repo: hdl/MINGW-packages
```

> This repository contains references to package recipes (PKGBUILD files) for [electronic design automation (EDA)](https://en.wikipedia.org/wiki/Electronic_design_automation) tools/projects to be built as MinGW-w64 targets on [MSYS2](https://www.msys2.org/) (MINGW32 and MINGW64). The main purpose is coordination of contributions for upstreaming all tools/projects to official MSYS2 repositories, and having them updated periodically. The default package manager (`pacman`) allows installing multiple tools at once through group `mingw-w64-*-eda` ([i686](https://packages.msys2.org/group/mingw-w64-i686-eda)|[x86_64](https://packages.msys2.org/group/mingw-w64-x86_64-eda)) . Find further details, along with usage and contribution guidelines at [hdl.github.io/MINGW-packages](https://hdl.github.io/MINGW-packages).
