### ISSUE TITLE
VHDLproc - VHDL preprocessor following VHDL-2019 directives

### ISSUE THREAD

**Issue by nobodywasishere** [VHDL/news#28]
```yaml
ref: https://github.com/nobodywasishere/VHDLproc
tags: [python, 2019, preprocessor]
repo: nobodywasishere/VHDLproc
```

I recently worked on rewriting this from scratch to go from C-style directives to VHDL-2019 directives, and it was a lot of fun. A bonus is now it is available as both a commandline and python library, and available on pip.
