### ISSUE TITLE
Open Source Verification Bundle (OSVB)

### ISSUE THREAD

**Issue by umarcor** [VHDL/news#30]
```yaml
ref: https://umarcor.github.io/osvb/
tags: [osvb, vunit, svunit, cocotb, osvvm, uvvm, renode, ghdl, verilator, iverilog, yosys]
repo: umarcor/osvb
```

> OSVB gathers the [most popular](https://larsasplund.github.io/github-facts/) open source verification [Frameworks and Methodologies](https://umarcor.github.io/osvb/intro/frameworks.html#projects) for VHDL and System Verilog: cocotb, OSVVM, SVUnit, UVVM, VUnit. Each of them was created and is maintained by different groups of people, in different contexts and with different backgrounds. All evolved into standalonish solutions involving build and test execution helpers, along with verification components for standard interfaces. However, each project prioritised certain features, while others didn’t receive so much care. The purpose of this bundle is twofold:
>
> - Allow users of any of the frameworks/methodologies to share some plumbing with others, so that communities can share testbenches written in any framework without having to learn a new workflow from scratch.
>
> - Reduce the maintenance burden of the projects by focusing on the features which are unique to a particular framework/methodology, instead of reinventing the wheel.
