### ISSUE TITLE
What Can GitHub Tell Us About the HDL Industry? (Part 2)

### ISSUE THREAD

**Issue by eine** [VHDL/news#6]
```yaml
ref: https://larsasplund.github.io/github-facts/verification-practices.html#frameworks
repo: LarsAsplund/github-facts
related: [2, 3]
tags:
- cocotb
- osvvm
- study
- uvm
- uvvm
- verification
- vunit
```

The second article/chapter was published:

> In the [first article](https://www.linkedin.com/pulse/what-can-github-tell-us-hdl-industry-lars-asplund?lipi=urn%3Ali%3Apage%3Ad_flagship3_pulse_read%3BLj9O1E2UQKWn4ypZ1%2F1dcg%3D%3D) about our GitHub study we focused on the presence of tests in HDL repositories. This time we're looking into what standard verification frameworks are being used. The main conclusions are that:
>
> - [VUnit](http://vunit.github.io/) is the most used verification framework for professional and academic VHDL repositories on GitHub.
> - Most repositories using more than one framework use VUnit and [OSVVM](https://osvvm.org/).
> - More than half of the repositories using OSVVM also use VUnit.
> - [UVM](https://www.accellera.org/community/uvm/) is not combined with any other framework.
>
> The [full story](https://larsasplund.github.io/github-facts/) and [the code](https://github.com/LarsAsplund/github-facts) used to derive these facts are part of an [open science](https://en.wikipedia.org/wiki/Open_science) project. Everything can be reviewed and the results can be repeated. We encourage [contributions](https://github.com/LarsAsplund/github-facts/pulls) and [suggestions](https://github.com/LarsAsplund/github-facts/issues) on other interesting facts that we should derive.
> 
> -- *Lars Asplund* https://www.linkedin.com/pulse/what-can-github-tell-us-hdl-industry-part-2-lars-asplund/
